### ISSUE TITLE
What about those keywords suffix with a colon?

### ISSUE THREAD

**Issue by hbin** [lewang/fic-mode#2]
fic-mode is what I want to show the TODO-like words. But some of my workmates are used to add a colon after those words. And those keywords won't be highlight suffix with a colon. I will thank you to fix this. ;)

**Comment by joca-bt** [comment]
```TODO,```? I still get ```TODO``` highlighted here.

**Comment by z0rch** [comment]
@joca-bt, `TODO,` is highlighted, but `TODO:` is not.

I guess a workaround would be to do something like that:

```elisp
(setq fic-highlighted-words '("TODO" "TODO:" "FIXME" "FIXME:" "BUG" "BUG:"))
```

**Comment by lewang** [comment]
that depends on the syntax table
